### ISSUE TITLE
Tab subtitles

### ISSUE THREAD

**Issue by RedShift1** [cristijora/vue-form-wizard#100]
Support for tab subtitles would be nice, [like demonstrated here](https://uxplanet.org/wizard-design-pattern-8c86e14f2a38): 

![form-wizard-tab-subtitles](https://user-images.githubusercontent.com/3098010/33118157-37a7c618-cf6b-11e7-963e-f6825cbc9521.png)

Could probably be easily accomplished if HTML is allowed in the title. The subtitle can then be wrapped in a div (or whatever) and styled via CSS.

**Comment by cristijora** [comment]
You can pretty much achieve this look by using the `step` slot
```html
<wizard-step 
                slot-scope="props"
                slot="step"
                :tab="props.tab"
                :transition="props.transition"
                :index="props.index">
                <div slot="title">
                  <div style="color: #3498db">
                    {{props.tab.title}}
                  </div>
                  Subtitle
                </div>
            </wizard-step>
```

Example https://jsfiddle.net/bt5dhqtf/1564/

However the approach is pretty limited since you would basically have to do some checks.
If you iterate through the tabs to display them, then this could be quite easy with a method
https://jsfiddle.net/bzfb4p8u/19/

```
<span>
    {{getSubTitle(props.index)}}
</span>
```

```js
getSubTitle(index){
    return this.tabs[index].subtitle
}
```

If you need something more flexible, feel free to open a PR and add a prop on this component https://github.com/cristijora/vue-form-wizard/blob/master/src/components/TabContent.vue
which could be an object with `additionalInfo` where you could pass the subTitle or other information which you might need. Then, the declaration of the step could be better like this

```html
<wizard-step 
                slot-scope="props"
                slot="step"
                :tab="props.tab"
                :transition="props.transition"
                :index="props.index">
                <div slot="title">
                  <div style="color: #3498db">
                    {{props.tab.title}}
                  </div>
                  {{props.tab.additionalInfo.subTitle}}
                </div>
 </wizard-step>
```
