### ISSUE TITLE
Events: prevent default behaviour

### ISSUE THREAD

**Issue by ibanjo** [cristijora/vue-form-wizard#135]
Hi,
I don't know if I went wrong somewhere, but I cannot find anywhere in the documentation any caveat about using Vue's default event modifiers. What I'm trying to do is to show a confirmation popup when switching between tabs, and preventing the switch in case, say, some flag is set.
In my template I expect to write something like:

```vue
<form-wizard ref="myWizard" @on-change.prevent="onTabChanged">
    <tab-content v-for="tab in tabs" :key="tab.id" :title="tab.name">
    </tab-content>
</form-wizard>
```

And, in the methods Object:

```javascript
methods: {
    onTabChanged: function (previous, next) {
        if(this.myFlag)
            this.$refs.myWizard.changeTab(previous, next);
    }
}
```

What I get is a `[Vue warn]` that says `"TypeError: $event.preventDefault is not a function"`. The same holds for the `.stop` modifier. Of course, if I do not stop the event propagation, it keeps on firing "infinitely", that is until the maximum call stack size is reached.

On the other hand, the `.once` modifier seems to work fine, but it does not solve the problem. Any clue?

**Comment by cristijora** [comment]
Hi @ibanjo 
There is a difference between native events (e.g `@input` on `<input/>` tag or `@change` on some other native html tag) and custom Vue events which are emitted through `this.$emit`.

The native events have an `$event` object which is native from html/js and contains several options like preventDefault and so on. Vue simply has some wrappers around it with the modifiers you tried above `stop, prevent, once` and so on.

Since `on-change` event from the wizard is simply a custom event used with `this.$emit`, it doesn't have a reference to an `$event` object and therefore you can't use modifiers with it.
This rule applies to any custom component that uses `this.$emit`

**Comment by ibanjo** [comment]
OK, sorry, I was not fully aware of this. I guess the only way to achieve a "confirm before change" behaviour is to use custom buttons instead of the default ones. Should I find an elegant (and relevant) workaround, I will post it here.

Thank you again

**Comment by cristijora** [comment]
In order to achieve the behaviour you want, you need a bit more code to do that. You would mainly use slots for that. Probably both for steps and for navigation buttons.

Here is a starting point https://jsfiddle.net/bt5dhqtf/1696/

**Comment by ibanjo** [comment]
Awesome, thank you again! Perhaps it might be helpful to introduce this example in the official documentation. Maybe it is not so unusual a feature to require.
