### ISSUE TITLE
Give the next nav pill same functionality as the "next" button

### ISSUE THREAD

**Issue by odeland** [cristijora/vue-form-wizard#159]
During tests with a customer, I found that some users are naturally drawn to the nav pill of the next step, instead of going for the next button at the bottom, but clicking it is disabled unless the step is already completed.

I tried messing around with slots without success. I also know that I can activate all tabs, but I find that the idea of prev/next flow is broken that way, I would only want the nav pill following the currently active tab to be able to continue the progress.

I'm not sure if I'm being clear, let me know if this is possible using scoped slots or if I need to fork this to achieve it.

**Comment by cristijora** [comment]
Hi @odeland You can indeed achieve that with the step slot.
http://vuejs.creative-tim.com/vue-form-wizard/#/?id=step-slot

Here's a demo for that. Might not be perfect but good as a starting point. I might add this functionality later on but for now you could use such an implementation.

```js
let wizard = this.$refs.wizard;
     if(index === wizard.activeTabIndex + 1){
       wizard.nextTab()
     } else {
      navigateMethod();
     }
```

Here, we verify whether the index is next to the active one. If it is, we trigger the internal wizard navigation (nextTab) which is used for the next button. Otherwise the default step navigation is used as fallback. 

Hope this helps

**Comment by odeland** [comment]
Looks good, thanks for the demo, I just made one small correction and passed index to navigateMethod on line 13.

https://jsfiddle.net/bt5dhqtf/1866/
