### ISSUE TITLE
Example: Refactor wizard steps into components

### ISSUE THREAD

**Issue by obiwarn** [cristijora/vue-form-wizard#21]
Hey,

I am new to Vue. 

I try to refactor your forms example:
https://jsfiddle.net/CristiJ/bt5dhqtf/286/

How can I get the wizard steps into separate components? Do I need to pass the model and formOptions as props?

Thank you!

**Comment by cristijora** [comment]
@obiwarn You cannot extract the steps into components (circles from above) since those are handled by the wizard component but you can extract the tab-contents. 
There are 2 approaches of doing this:
1. Either with `vue-router`  See https://jsfiddle.net/bt5dhqtf/267/
Instead of `First` `Second` you can have your own components with the content you want
2. Extract the content from each tab-content into a separate component. Since the example from above already does that through `vue-form-generator` what you can do is to extract some `data` in separate files. Here is an example with element-ui https://jsfiddle.net/bt5dhqtf/532/

**Comment by obiwarn** [comment]
Thank you! 

2. did the trick for me.
