### ISSUE TITLE
How to disable button back in the last tab?

### ISSUE THREAD

**Issue by agilBAKA** [cristijora/vue-form-wizard#31]

**Comment by cristijora** [comment]
@agilBAKA You can do it via `refs` 
https://jsfiddle.net/bt5dhqtf/691/

It's not a very clean solution because you have to write the button yourself and also have the ref, but this will be possible in the next release with scoped slots
```
 <div slot="footer" scope="props">
  <button v-show="!props.isLastStep" @click="props.nextTab()>Back</button>
  </div>

```
The only disadvantage is that once you customize this stuff, you will have to wire up the button clicks and the UI but it will be fully customizable. Until the next release you could use the solution from above.

**Comment by cristijora** [comment]
@agilBAKA 
The other option is possible now due to the impleemntation from #27 
Example
```html
 <template slot="footer" scope="props">
        <div class=wizard-footer-left>
          <wizard-button v-if="props.activeTabIndex > 0 && !props.isLastStep" :style="props.fillButtonStyle">Previous</wizard-button>
        </div>
        <div class="wizard-footer-right">
          <wizard-button @click.native="props.nextTab()" class="wizard-footer-right" :style="props.fillButtonStyle">Next</wizard-button>
        </div>
      </template>
```

Fiddle https://jsfiddle.net/bt5dhqtf/710/
It's up to you which option you chose, but the last one is more modular and allows changes easier as well as does not depend on refs which have their issues.

**Comment by cristijora** [comment]
Released https://github.com/cristijora/vue-form-wizard/releases/tag/v0.6.2
Also see [docs about this part](https://cristijora.github.io/vue-form-wizard/#/?id=footer-slot)

**Comment by agilBAKA** [comment]
Thank you @cristijora

**Comment by gittrolo** [comment]
I should disable the button at the last step. Can you give a complete example using the "wizard-button" ?
Thanks
