### ISSUE TITLE
tab changes position when toggled

### ISSUE THREAD

**Issue by Chinese1904** [cristijora/vue-form-wizard#36]
Hi everyone,

I struggle figuring out how I can keep the toggled tab at the same position. Take a look at this fiddle:
https://jsfiddle.net/bt5dhqtf/747/

As you can see, when you press "Log Out Toggle" the toggled tab's position will change to before the last tab.

Any help would be greatly appreciated!

Chris

**Comment by cristijora** [comment]
@Chinese1904 Thanks for reporting. Unfortunately I don't think I can fix that since I cannot control the order in which the children are rendered. I would suggest using a `v-for` in combination with `component :is` for such cases since the order is predicatable in this case

https://jsfiddle.net/bt5dhqtf/758/

You can organize steps into components this way which I think also leads to cleaner more declarative code. The only issue I can fix here is that the tab circle has no border when removed/added if you went through more steps.

**Comment by Chinese1904** [comment]
Thanks a lot for pointing out this alternative with the fiddle. Helped a lot!
