### ISSUE TITLE
Question: Disable everything on load

### ISSUE THREAD

**Issue by mjcombalicer** [cristijora/vue-form-wizard#48]
Hello,

I just wanted to ask the best way of loading the form with disabled fields and next step button and have an 'edit' button to enable all the fields?

The scenario is that if multiple users have opened the same record at a time one user should be able to edit the record and fires off an event to notify the others that the record is currently on edit mode.

Thanks!

**Comment by cristijora** [comment]
Hi @mjcombalicer 

The fields should be trivial to disable but it depends on what you use for forms.
Here is an example with vue-form-generator.
https://jsfiddle.net/bt5dhqtf/1200/

The wizard buttons however might be trickier since you have to redefine the buttons with a scoped slot yourself.  https://cristijora.github.io/vue-form-wizard/#/?id=footer-slot
It might be a bit of boilerplate for the wizard footer but then you have full control over the buttons. You can disabled/hide and do whatever you need with them. 

If you have a proposal for this, I would probably implement it since I think it might be useful to have disabled steps.

**Comment by mjcombalicer** [comment]
Thanks @cristijora,

Your example is perfect as I am using vfg. 

In terms of a proposal, can I ask what you mean? Please excuse my ignorance as I'm fairly new to this.

**Comment by cristijora** [comment]
I was asking whether you have a proposal on how to improve this. The downside of the implementation I showed you is that you have to redefine the footer content.

I was thinking of maybe providing a disabled prop for `tab-content`
`<tab-content disabled>` which would disable the next and prev button

**Comment by mjcombalicer** [comment]
Hi @cristijora 

I see what you mean now. 

From how I see it I think it is best if there is hierarchy to it.

For example with my question, the form itself will be loaded on disable. I think a disabled option within form-wizard (I'm just guessing here) should be available and all tab-content will inherit that property.

Then for tab-content is something you mentioned above which means that all fields within that tab will inherit the prop.

I'm not sure if that makes sense.

**Comment by cristijora** [comment]
@mjcombalicer After looking a bit into this, I think sticking to the initial example I gave above would be the best idea. Adding stuff on top of it would only make it harder to maintain.
