### ISSUE TITLE
How to always enable the click event on nav pills?

### ISSUE THREAD

**Issue by theKhorshed** [cristijora/vue-form-wizard#52]
I really like the vue-form-wizard component, great works!

I would like to enable the nav-pills for the tabs to be always clickable and users can go to any step by clicking on any nav-pill.

The current behavior is when a user visits some tabs only then the previous nav-pills become clickable.

Please shed some lights on this.

Thanks in advance

**Comment by pimboden** [comment]
I think this should not be part of a wizard... If you need that, then you should use normal tab control... A wizard should guide you forward.. see the [vue-tabs](https://github.com/cristijora/vue-tabs) from @cristijora  .
I mean, if @cristijora  is implementing this, then it'll need to be configurable... because for my use case it would be actually wrong if the user can click any the step.

**Comment by cristijora** [comment]
@pimboden thanks for the answer. I wanted to write the same thing. 
Although I agree with this, maybe there are use cases where you want to show a wizard for informational purposes. 
This behavior @theKhorshed can be achieved with scoped slots and some custom logic but I wouldnt include it as a prop/option in the wizard as its not a default expected behavior as @pimboden said

**Comment by theKhorshed** [comment]
Thanks for your reply and you guys are right.

Actually, I need this the default wizard behavior when a user submits the form for the first time and also the tab like behavior when the users come back to edit the form later.

I'm doing this right now via the following code on mount
`
this.$refs.wizard.changeTab(0, 3)
this.$refs.wizard.changeTab(3, 0)
`
Let me know if there is any better approach. Also I think a prop/option would be a nice addition to the component.

**Comment by cristijora** [comment]
Yes @theKhorshed that can be an option. Another more generic option would be this one
```js
var tabs = this.$refs.wizard.tabs;
tabs.forEach((tab)=>tab.checked = true)
this.$refs.wizard.maxStep = tabs.length;
```

**Comment by theKhorshed** [comment]
Thanks a lot @cristijora

**Comment by yogithesymbian** [comment]
> Yes @theKhorshed that can be an option. Another more generic option would be this one
> 
> ```js
> var tabs = this.$refs.wizard.tabs;
> tabs.forEach((tab)=>tab.checked = true)
> this.$refs.wizard.maxStep = tabs.length;
> ```
> 
> https://jsfiddle.net/bt5dhqtf/1278/

greats!...

**Comment by yogithesymbian** [comment]
on documentation we can do like these
```
this.$refs.wizardFirst.activateAll()
```
