### ISSUE TITLE
Dynamic tab-content

### ISSUE THREAD

**Issue by SmarterPhoneLabs** [cristijora/vue-form-wizard#54]
Hi this may have been answered elsewhere, but I cant find where.
I have a security system implemented in my app where certain tabs are disabled if users cant access them.
How I have set this up is with v-if statements inside the tab-content items.
Technically, this works, however the problem is that its messing with the navigation item size.

For example:
I have 3 total tabs
Tab 1 is wide open
Tab 2 is secured by permission ID
Tab 3 is secured by permission ID

If I dont have permissions for tab 2&3 when I load the page, I would expect to just have the Finish button, but I get the next button instead and I have to still click it multiple times to get the finish button.

I hope this makes sense.

**Comment by cristijora** [comment]
This makes sense @SmarterPhoneLabs 
This requires an implementation in order to work as you want. 
I would imagine something like this.
```html
<vue-form-wizard>
 <tab-content>
   tab 1
<tab-content>
  <tab-content :disabled="true">
   tab 2
<tab-content>
</vue-form-wizard>
```
I would be really glad if you could make a PR (of course if you want to)
The implementation of the disabled option would basically require a prop for `TabContent`
and some adjustments on the `nextTab/prevTab` methods
https://github.com/cristijora/vue-form-wizard/blob/master/src/components/FormWizard.vue#L276
where we would need to find the next "not disabled" tab rather than calling `index + 1`. Same logic would apply for `prevTab`

Besides this, maybe some additional "disabled" state styles should be added.

**Comment by cristijora** [comment]
A more simplistic option which doesn't require any implementation would be this one 
https://jsfiddle.net/bt5dhqtf/1319/
which simply hides steps based on a value
