### ISSUE TITLE
themify-icons style shifted to the top

### ISSUE THREAD

**Issue by gyamxxx** [cristijora/vue-form-wizard#9]
Sorry, I'm poor English.
Your library is awesome 👍.
By the way, I'm using bulma.css and your library, but themify-icons style shifted to the top like this.
![icon](https://cloud.githubusercontent.com/assets/6592208/26281051/4fbdb6d6-3e25-11e7-9567-425f54f80ef6.png)
Maybe .icon class is appreciated with bulma.css.
How can I fix it? plz help me.

**Comment by cristijora** [comment]
Please make jsfiddle if you can. That would help a lot

**Comment by cristijora** [comment]
Also themify-icons are just an example. You can use pretty much any icons library as long as it's css classes. Here is an example with font-awesome icons https://jsfiddle.net/bt5dhqtf/349/

**Comment by gyamxxx** [comment]
@cristijora 
Thank you for reply.
Sorry, themify-icons is not related with this problem.
bulma.css's nav class and icon class are affected with vue-form-wizard.css.
It's my jsfiddle example.
https://jsfiddle.net/bt5dhqtf/353/

**Comment by cristijora** [comment]
Yeah I see the issue. Unfortunately I cannot control too much what other css libraries override.
Here is a short term fix https://jsfiddle.net/bt5dhqtf/360/ where certain stuff can be overriden for the wizard parts. By the way, vue-form-wizard doesn't affect any other global css because everything is under `.vue-form-wizard` class but in this case other css affects the wizard. 

I will try to rename some classes maybe so it's more specific (e.g form-wizard-nav instead of nav) and so on

**Comment by gyamxxx** [comment]
Thanks @cristijora .
I'll attempt your jsfiddle sample for now.

**Comment by gyamxxx** [comment]
@cristijora 
I confirmed it.Thank you so much !!
